### ISSUE TITLE
Upgrade model to ES 6.x

### ISSUE THREAD

**Issue by lukas-vlcek** [BitScoutOrg/elasticsearch-templates#99]
- [x] Index templates use "index_patterns" instead of "template" ES 6.x (#98)
- [x] Option `include_in_all` not supported in ES 6.0.0 and later (#101)
- [x] `_all` field not supported starting in ES 6.x (#46)
- [x] the `_default_` mapping is deprecated in ES 6.x and completely removed in ES 7.x (#111)
- [x] ES index type deprecation in ES 6.x and removal in ES 7.x (#84)
- [x] add tests for backward compatibility with ES 5.x (implemented in eda925b and b31049a)
- [x] bump model version (ac07c1d)
